---
bibliography: "input/bib/pref-redis-colmex.bib"
lang: es
---

# Antecedentes

## Conceptos y Medición de las Preferencias Redistributivas

Las preferencias redistributivas se refieren a las actitudes de los individuos hacia la asignación de recursos dentro de la sociedad, especialmente en relación con las políticas destinadas a reducir la desigualdad de ingresos a través de impuestos y programas de bienestar social. Los conceptos y la medición de estas preferencias son multifacéticos, abarcando diversos marcos teóricos y hallazgos empíricos que destacan la interacción entre las características individuales, las normas sociales y las condiciones económicas. Un aspecto significativo de las preferencias redistributivas es el papel del interés propio y la percepción de justicia. La investigación en el área indica que los individuos a menudo basan su apoyo a la redistribución en su situación económica y en la legitimidad percibida de la distribución de la riqueza. @dimick_altruistic_2017 argumentan que los individuos distinguen entre ingresos obtenidos por "suerte" frente a "esfuerzo", lo que influye significativamente en sus preferencias por la redistribución. De manera similar, @kuziemko_elastic_2015 enfatizan la importancia de las preferencias de los votantes y las motivaciones subyacentes que impulsan estas preferencias, sugiriendo que el interés propio desempeña un papel crucial en la configuración de las actitudes hacia las políticas redistributivas. Esto se alinea con los hallazgos de @goni_fiscal_2011, quienes señalan que los factores culturales y contextuales también influyen en las preferencias redistributivas, con individuos en diferentes países exhibiendo distintos niveles de apoyo a la redistribución en función de sus normas sociales y condiciones económicas.


La medición de las preferencias redistributivas ha evolucionado significativamente, utilizando diversas metodologías de encuesta para capturar las actitudes de los individuos hacia la redistribución de ingresos. Las encuestas emplean distintos ítems que evalúan las preferencias por diferentes políticas redistributivas, permitiendo a los investigadores analizar cómo varían estas preferencias entre grupos demográficos y en distintos contextos económicos. Por ejemplo, @brooks_redistribution_2021 llevaron a cabo un análisis exhaustivo utilizando 12 ítems distintos relacionados con las preferencias redistributivas, aprovechando datos de alta calidad de los estudios nacionales electorales Estadounidenses. Este enfoque permite una comprensión matizada de cómo el partidismo y otros factores influyen en las actitudes hacia la tributación y la redistribución.  @meuleman_context_2019 analizó datos de encuestas transversales repetidas del British Social Attitudes (BSA) y la General Social Survey (GSS) para desentrañar las diferencias de cohorte y año en el apoyo a la redistribución de ingresos, destacando el impacto del contexto económico predominante en estas preferencias. Además, se han empleado enfoques experimentales para evaluar la elasticidad de las preferencias por la redistribución. @kuziemko_elastic_2015 realizaron experimentos de encuestas aleatorizadas para explorar cómo cambian las preferencias de los individuos en respuesta a cambios en las condiciones económicas percibidas y las normas sociales. Esta metodología permite una comprensión más dinámica de las preferencias redistributivas, revelando cómo los factores contextuales pueden influir significativamente en las actitudes de los individuos hacia la redistribución.

El estudio de las preferencias redistributivas a menudo implica examinar la influencia de factores demográficos, como el nivel de ingresos, la educación y el capital social. @mustofa_education_2023 destacan que una educación superior puede alterar las percepciones de justicia, afectando así las preferencias por la redistribución. De manera similar, @yamamura_norms_2015 discuten cómo las normas comunitarias y el capital social impactan en las actitudes de los individuos hacia la redistribución, sugiriendo que unos lazos comunitarios más fuertes pueden aumentar el apoyo a las políticas redistributivas. Esta noción se ve respaldada además por @lasarga_mobility_2022, quienes exploran cómo la desigualdad de ingresos y la presencia de minorías étnicas entre los pobres pueden influir en las preferencias públicas por la redistribución en América Latina. Las dinámicas de las preferencias redistributivas también están influenciadas por contextos económicos y políticos más amplios. @gonthier_parallel_2016 señala que durante las crisis económicas, las preferencias por la redistribución pueden cambiar a medida que los individuos reevalúan sus intereses materiales y valores fundamentales relacionados con la igualdad y la justicia social. Además, el concepto de "altruismo parroquial", discutido por @rueda_food_2018, sugiere que los individuos pueden priorizar las preferencias redistributivas basándose en su entorno social inmediato, particularmente en el contexto de la inmigración y la asignación de recursos. Esto indica que las preferencias redistributivas no son estáticas, sino que responden a los cambiantes paisajes económicos y sociales.

En el contexto de América Latina, las preferencias redistributivas están moldeadas por una combinación única de factores históricos, económicos y sociales que contribuyen a los altos niveles de desigualdad de la región. La región se ha caracterizado durante mucho tiempo por marcadas disparidades de ingresos, con un coeficiente de Gini significativamente más alto que en otras partes del mundo [@goni_fiscal_2011]. Esta desigualdad ha influido en las actitudes públicas hacia la redistribución, observándose preferencias variables entre los distintos países. Por ejemplo, @franetovic_preferences_2022 destacan que las preferencias por la redistribución de ingresos en América Latina han evolucionado entre 2008 y 2018, reflejando cambios en las condiciones económicas y el sentimiento público hacia la desigualdad. Además, la percepción de la corrupción juega un papel crítico en la configuración de las preferencias redistributivas. @hauk_preception_2022 encontraron que en los países con altos niveles de corrupción percibida, el apoyo público a la redistribución tiende a ser más fuerte, ya que los ciudadanos a menudo ven la redistribución como un medio para contrarrestar los efectos negativos de la corrupción en la desigualdad económica. Esta relación subraya la complejidad de las preferencias redistributivas en la región, donde la confianza institucional y las percepciones de la eficacia gubernamental influyen significativamente en las actitudes públicas hacia las políticas redistributivas.

Los estudios específicos por país iluminan aún más las sutilezas de las preferencias redistributivas. Por ejemplo, Brasil ha experimentado cambios significativos en las políticas redistributivas, lo que ha contribuido a una reducción de la desigualdad de ingresos en las últimas dos décadas. Sin embargo, la persistencia de altos niveles de desigualdad indica que los sistemas redistributivos aún se están desarrollando y enfrentan numerosos desafíos [@lasarga_mobility_2022]. En contraste, países como Argentina y Uruguay han implementado sistemas de protección social más robustos, que se han asociado con niveles más altos de apoyo público a la redistribución [@ocampo_social_2018]. Además, no se puede pasar por alto el papel de los movimientos sociales y las protestas en la configuración de las preferencias redistributivas. @justino_redistributive_2019 argumentan que fuertes preferencias redistributivas, junto con demandas insatisfechas de justicia social, han llevado a un aumento de las protestas en América Latina, destacando una desconexión entre las expectativas públicas y la acción gubernamental. Esta dinámica ilustra cómo las preferencias redistributivas no son solo un reflejo de actitudes individuales, sino que también están influenciadas por contextos sociopolíticos más amplios.

## Factores individuales asociados a las preferencias redistributivas 

### Interés propio

La literatura ha documentado de manera sólida los factores individuales que explican las preferencias redistributivas [@lindh_public_2015; @curtis_how_2015; @langsaether_more_2020; @brooks_why_2010]. Las explicaciones basadas en el interés propio, la posesión de recursos económicos o la exposición al riesgo, explican por qué los individuos con ingresos bajos, menos recursos y mayor inseguridad laboral tienden a apoyar la redistribución [@meltzer_rational_1981; @rehm_risks_2009]. Así, el estatus socioeconómico se posiciona como uno de los principales motores de las preferencias redistributivas. El modelo de Meltzer y Richard [-@meltzer_rational_1981], una extensión del teorema del votante mediano, propone el interés propio como el mecanismo clave para explicar las preferencias redistributivas. Según esta teoría, el ingreso de mercado refleja los intereses materiales de los votantes, cuyas preferencias dependen de su posición relativa a la mediana de ingresos. Así, quienes se encuentran por debajo de esta mediana suelen mostrar una mayor inclinación por la redistribución, en comparación con aquellos que están por encima. Es decir, quienes están en la parte inferior de la distribución de ingresos se benefician más de la redistribución y son menos afectados por los aumentos en la carga tributaria en relación con aquellos en la cima.

Empíricamente, la relación entre el ingreso y las preferencias redistributivas ha sido ampliamente estudiada. Investigaciones en Estados Unidos [@alesina_preferences_2010], Europa [@dimick_models_2018] y América Latina [@franetovic_preferences_2022] han respaldado las predicciones de esta perspectiva. Sin embargo, aunque existe abundante evidencia que apoya la hipótesis del interés propio, estudios recientes han mostrado resultados mixtos respecto a las preferencias de los grupos de altos ingresos y el rol del ingreso de mercado como principal impulsor del interés propio. Por ejemplo, un estudio sobre ciudadanos urbanos de Brasil encontró una relación positiva entre estatus socioeconómico y apoyo a la redistribución [@garcia-sanchez_creencias_2022]. Los autores sugieren que la mayor conciencia sobre la desigualdad entre personas adineradas y educadas, en contextos altamente desiguales como Brasil, fomenta posturas más altruistas respecto a la redistribución. Además, aunque las comparaciones internacionales han demostrado la esperada relación negativa entre ingresos y apoyo a la redistribución, también se han observado efectos nulos o incluso positivos en distintos ámbitos redistributivos, lo que refleja una variabilidad en las preferencias de los ricos entre diferentes sociedades [@steele_wealth_2022].

Otros estudios han argumentado que la riqueza, más que el ingreso de mercado, constituye una fuente más estable de interés propio, pero ha sido poco explorada en la literatura. @steele_wealth_2020 sostiene que la riqueza es una medida más amplia de los recursos económicos, ya que incluye todos los activos, que pueden subdividirse en "riqueza inmobiliaria" (propiedades como viviendas) y "riqueza financiera" (activos como cuentas de ahorro o acciones). Su evidencia sugiere que la riqueza financiera es más relevante que la inmobiliaria. Primero, los activos financieros proporcionan liquidez de manera más directa que la riqueza inmobiliaria, que a menudo está vinculada a hipotecas. Además, tanto la riqueza inmobiliaria como la financiera ejercen una influencia positiva, aunque heterogénea, en las preferencias redistributivas, a diferencia del ingreso de mercado. Steele sugiere que la riqueza ofrece una "red de seguridad", principalmente a través de herencias, lo que protege contra choques económicos y mejora las oportunidades de vida para las generaciones futuras [@steele_wealth_2022, p.4].

Adicionalmente, @rueda_who_2019 han señalado que la literatura sobre interés material ha priorizado el análisis del ingreso de mercado, mientras que la relevancia de las expectativas de ingresos futuros ha sido insuficientemente explorada. Los autores otorgan mayor importancia a los rendimientos del ingreso como función del capital humano (relacionado con el nivel educativo) y la experiencia laboral (relacionada con la edad). Su hipótesis sugiere que los individuos tienen conocimiento del ciclo de vida de su grupo educativo y, por tanto, las expectativas de ingresos futuros influyen negativamente en sus preferencias por la redistribución actual. Evidencia empírica basada en datos europeos ha mostrado que el ingreso futuro y las preferencias redistributivas están efectivamente asociadas de manera independiente al ingreso actual, lo que refuerza esta hipótesis.

### Valores

La dimensión normativa a nivel individual es clave para comprender las motivaciones y cómo estas se expresan en el comportamiento [@esser_integrative_2015]. Además, permite entender cómo las instituciones políticas cristalizan y, al mismo tiempo, pueden influir en las actitudes de los individuos hacia la redistribución económica [@edlund_democratic_2015]. La literatura sobre preferencias redistributivas ha tratado este dominio como una fuente independiente de motivación, en contraste con las explicaciones basadas en el interés material. Inspirado por la teoría sociológica de la acción, @esser_integrative_2015 sugieren que el paradigma del *homo economicus* se centra en las oportunidades, incentivos y expectativas racionales para explicar el comportamiento humano mediante el interés propio. Por el contrario, el paradigma del homo sociologicus asume que las reglas de acción institucionalizadas se aprenden a través de la socialización en el ámbito familiar y mediante interacciones sociales [@paskov_crossclass_2022].

La literatura también ha examinado los factores normativos bajo el concepto de valores, aunque en algunos estudios se utiliza de manera intercambiable con términos como creencias o ideología. Sin embargo, se ha argumentado que los valores como el igualitarismo económico —asociado con el principio de justicia de igualdad— difieren conceptual y empíricamente de la ideología política, representada comúnmente por el continuo izquierda-derecha [@feldman_understanding_2014]. De esta forma, los valores igualitarios pueden ser compartidos por individuos a lo largo de todo el espectro político. Por ejemplo, quienes son más igualitaristas tienden a mostrar mayor apoyo a la intervención gubernamental en la esfera social y económica [@feldman_humanitarian_2001]. Por otro lado, el humanitarismo, que refleja una orientación prosocial cercana al principio de justicia basada en la necesidad, se asocia con el apoyo a políticas de alivio de la pobreza y atención a las necesidades básicas [@feldman_humanitarian_2001]. Aunque ambos enfoques normativos comparten preocupaciones sobre la justicia social, los valores humanitarios suelen promover apoyo a políticas específicas en lugar de la redistribución generalizada. 

Los valores igualitarios se asocian con un mayor apoyo a la redistribución. Por ejemplo, la literatura sobre justicia distributiva ha demostrado que una menor justificación de la desigualdad económica está vinculada a un mayor igualitarismo [@Castillo2011]. Además, un estudio realizado en seis sociedades industriales occidentales demostró que una mayor adhesión a los valores igualitarios está fuertemente asociada con el apoyo a la participación del gobierno en servicios sociales, controles de precios y subsidios para necesidades básicas [@breznau_economic_2010]. De manera similar, un estudio sobre países europeos muestra que el igualitarismo incrementa la demanda de impuestos progresivos y el gasto social del gobierno [@svallfors_government_2013]. Asimismo, la evidencia de países europeos ha mostrado una asociación más fuerte entre el igualitarismo y las preferencias políticas entre los individuos de clases altas, sugiriendo que un mayor riesgo económico puede debilitar el vínculo entre los valores humanos abstractos y la redistribución [@Kulin2013]. Además, la relación del igualitarismo se ha abordado en las preferencias de políticas de salud, donde un mayor igualitarismo predice un mayor apoyo a la provisión pública de salud y un mayor gasto social en salud preventiva, pero un nulo apoyo a los impuestos progresivos para políticas de salud [@Azaretal2018].

Por otro lado, en cuanto a los valores humanitarios, la evidencia ha mostrado que, entre los ciudadanos estadounidenses, aquellos con valores humanitarios más fuertes tienden a apoyar políticas centradas en las necesidades de los ancianos y en el alivio de la pobreza [@feldman_humanitarian_2001]. Los autores argumentan que los valores humanitarios no son ciegos ante la desigualdad social, sino que racionalizan los problemas sociales como parte de la condición humana. A pesar de las preocupaciones compartidas sobre la justicia entre los enfoques humanitarios e igualitarios, el enfoque en las necesidades por parte de los valores humanitarios conduce al apoyo de políticas específicas, en lugar de la redistribución como medida para alcanzar el principio de igualdad. En esta línea, un estudio multinacional en 28 países ha demostrado que una sólida adhesión a los valores humanitarios se asocia con una mayor disposición a pagar impuestos para un sistema de salud universal, además de moderar la influencia negativa de la exposición al riesgo [@Maldonadoetal2019].


## Contexto y cambio de preferencias en América Latina

El contexto en donde viven las personas también tiene la capacidad de afectar su apoyo a las políticas redistributivas [@alesina_ethnic_2005; @kenworthy_inequality_2008; @svallfors_worlds_1997]. Si bien existen diferencias entre personas en función de sus características, también se han evidenciado grandes disparidades en el apoyo a la redistribución entre países y regiones del planeta. A nivel mundial, América Latina se ha tendido a posicionar como una de las regiones con mayor apoyo redistributivo [@dion_economic:_2010], a pesar de mostrar bajas en sus desigualdades económicas durante las últimas décadas [@holland_easy_2017; @lustig_declining_2013]. De todas formas, existe una importante heterogeneidad al interior de la región, con países con altas preferencias redistributivas—como Chile, Uruguay, Costa Rica y República Dominicana—y otros con bajo acuerdo con la redistribución—Venezuela, Paraguay, Ecuador y Bolivia, entre otros [@durakiewicz_reducing_2018]. Variados determinantes a nivel nacional en términos económicos, político-institucionales y socioculturales han sido relevados en el campo de la justicia distributiva, en búsqueda de explicar las variaciones en las preferencias redistributivas de las personas.

### Determinantes económicos

En términos económicos, uno de los factores mayormente estudiados es la desigualdad económica de los países. Desde la economía neoclásica, la previamente mencionada teoría del votante mediano de @meltzer_rational_1981 comenzó abordando esta relación, estableciendo que a medida que la desigualdad de los países es mayor, mayores serán las preferencias redistributivas de las personas. Según este enfoque, esta asociación estaría dada por una mayor distancia entre el votante de ingresos medianos respecto al votante de ingresos medios en contextos de mayor desigualdad, aumentando la población beneficiada por la redistribución y así su acuerdo con ella. Aunque algunos estudios han identificado una relación positiva entre la desigualdad y las preferencias redistributivas [@schmidtcatran_economic_2016], gran parte de la evidencia en torno a la justicia distributiva no encuentra una asociación clara [@bowles_reciprocity_2000; @luebker_income_2014], o incluso muestra un aumento en la tolerancia hacia la desigualdad en contextos donde esta es más pronunciada [@castillo_legitimacy_2010; @mijs_paradox_2019; @schroder_income_2017]. La falta de respaldo empírico hacia la teoría del votante mediano se explica por los supuestos en los que se basa: que los individuos son conscientes de la distribución de recursos en la sociedad y reconocen su posición relativa dentro de dicha distribución. Existe amplia evidencia que señala una desconexión entre la desigualdad real en los países y su percepción por parte de los ciudadanos [@bartels_unequal_2016; @gimpelson_misperceiving_2018; @kenworthy_inequality_2008; @trump_income_2023], así como sesgos en la autopercepción del estatus social, con una tendencia generalizada a ubicarse en las posiciones medias de la estructura social, aun cuando objetivamente no pertenezcan a dichos segmentos [@evans_subjective_2004].

Este aspecto guarda especial relevancia para América Latina, en tanto por décadas se ha ubicado como la región más desigual del planeta [@mann_explaining_2007]. Si bien se evidenció una disminución de sus niveles de inequidad económica durante los años 2000 [@holland_easy_2017; @lustig_declining_2013], en el presente Latinoamérica continúa situada entre las zonas con mayor desigualdad, siendo sólo superada por África Subsahariana y Medio Oriente y Norte de África [@chancel_world_2022]. @franetovic_preferences_2022 evidenciaron las complejidades que la relación entre desigualdad objetiva y subjetiva presenta para la región. Sus análisis dan cuenta de la escasa aplicabilidad de teorías racionalistas clásicas, como la del votante mediano, en tanto países con mayor coeficiente Gini —indicador comúnmente utilizado para medir desigualdad económica—no se encuentra relacionado a una mayor demanda redistributiva por parte de las personas [@franetovic_preferences_2022]. Más allá de sus niveles agregados, sería la estructura de desigualdad la que podría jugar un rol más importante, referente a la distancia económica entre las clases medias, con respecto a aquellas ricas y pobres [@lupu_structure_2011]. En países de la región donde los estratos medios se ubican más próximos a las clases desposeídas, mayor tiende a ser el apoyo redistributivo de sus ciudadanos [@borges_selfinterest_2022].

Un determinante nacional menos estudiado, pero relevante en la configuración del apoyo a la redistribución, es el desarrollo económico de los países. Tal como lo propone @inglehart_silent_1971, el desarrollo económico generado a partir de los procesos de modernización de los países ha estado fuertemente vinculado a la promoción de valores postmaterialistas. El auge en la cobertura de necesidades básicas se asocia entonces a proyectos de vida menos determinados por cuestiones materiales económicas dando paso a otro tipo de preocupaciones entre las personas, enfocadas en la promoción de la autonomía y la satisfacción personal [@inglehart_changing_2008]. Justamente, estos son factores que @gelissen_popular_2000 ha visto estrechamente relacionados con las preferencias por redistribución de las personas. La evidencia muestra que América Latina ha visto una trayectoria similar entre modernización, valores postmaterialistas y acuerdo con la redistribución. @franetovic_preferences_2022 dan cuenta cómo, sostenidamente en el tiempo, los países más ricos de la región—Chile, Uruguay, Costa Rica y Panamá—concentran altos niveles de acuerdo con la redistribución, mientras que aquellos de menor PIB per cápita—Bolivia, Guatemala y Honduras—se caracterizan por tener poblaciones con bajas preferencias redistributivas. 

### Determinantes político-institucionales

La literatura también reconoce la importancia de factores político-institucionales en el apoyo de las personas hacia la redistribución. El primero de ellos, comúnmente estudiado, corresponde al tipo de régimen de bienestar de los países. Según @espingandersen_three_1990, el estado de bienestar corresponde al conjunto de políticas sociales que determinan la desmercantilización de los individuos, la estratificación social y la relación entre Estado, mercado y familia. Considerando el origen del concepto, su discusión está marcada por una fuerte tradición occidental en países desarrollados. En ese contexto, se ha evidenciado que los regímenes de bienestar son importantes determinantes en las actitudes distributivas de las personas: mientras los regímenes socialdemócratas—universalistas y mayormente redistributivos—albergan un alto apoyo a la redistribución, en los liberales—subsidiarios y con acotada participación estatal en la provisión de servicios—éste tiende a ser mucho más acotado [@svallfors_worlds_1997].

Si bien la literatura de estado de bienestar y sus sistemas de clasificación está enfocada en países industrializados, también existen desarrollos teóricos adaptados a la realidad latinoamericana. Este contexto requiere consideraciones adicionales, al estar marcado por la existencia de zonas donde el Estado es prácticamente inexistente, una acotada porción de la población en el mercado laboral formal, y grupos de familiares y redes de apoyo como principales productores de bienestar [@gough_insecurity_2004]. Uno de los más destacados corresponde a la tipología desarrollada por @martinezfranzoni_welfare_2008. En función de sus niveles de mercantilización, desmercantilización y desfamiliarización, los países latinoamericanos son distinguidos entre regímenes productivistas, proteccionistas e informales-familiares. Si bien hasta la fecha no existen mayores intentos por analizar diferencias según regímenes de bienestar dentro de la región, @franetovic_preferences_2022 reportan que dicha distinción no estaría asociada a diferencias significativas en el apoyo a la redistribución de las personas al interior de la región.

También desde una arista político institucional se ha revelado la importancia que tiene la confianza institucional y la percepción de corrupción en el apoyo a la redistribución [@yamamura_trust_2014]. Esto guarda especial relevancia en una región como América Latina, considerando la fragilidad de sus instituciones [@portes_institutions_2010] y los elevados y ascendentes índices de corrupción percibida por parte de sus ciudadanos [@transparency_global_2019]. @hauk_preception_2022 sugieren que la percepción de corrupción es capaz de influir sobre las preferencias redistributivas de dos formas: reduciéndolas, en tanto se duda de la efectividad y justicia de las intervenciones gubernamentales, pero también aumentándolas, en la medida que se percibe disminuida la riqueza personal en relación con el promedio. @franetovic_preferences_2022 avalan el primer punto, mostrando cómo mayores niveles de confianza en el sistema político por parte de las personas se asocian a significativas alzas en su apoyo a la redistribución. Todo esto, sumado a la importancia que manifiesta la creencia en que el Estado posee la capacidad para redistribuir [@busso_preferences_2023], pone en evidencia que en América Latina la discusión sobre preferencias redistributivas no debe estar exclusivamente en las características de los ciudadanos, sino en su relación de éstos últimos con sus instituciones públicas.

El rol de la percepción de corrupción posee cierta ambivalencia en relación a las preferencias redistributuvas. Algunos estudios sugieren que la corrupción disminuye el apoyo a la redistribución, ya que la población puede desconfiar de que los recursos públicos sean utilizados de manera efectiva para reducir la desigualdad [@rothstein_all_2005]. La lógica detrás de esta argumentación es que, en contextos de alta corrupción, la ciudadanía percibe que el Estado es capturado por élites o grupos de poder, y, por tanto, es menos probable que las políticas redistributivas beneficien a los sectores más vulnerables. Como resultado, incluso aquellos que podrían beneficiarse de la redistribución podrían mostrarse escépticos hacia estas políticas. En América Latina, estudios recientes han explorado la relación entre estos factores, encontrando que la desconfianza en las instituciones y la percepción de corrupción afectan negativamente el apoyo a la redistribución [@holland_diminished_2018]. En contraste, otros estudios han argumentado que la percepción de corrupción puede incrementar la demanda de redistribución [@alesina_corruption_2005]. La lógica detrás de esta posición es que cuando la población percibe altos niveles de corrupción, también puede percibir que las desigualdades son producto de un sistema injusto, lo que incrementa el deseo de implementar políticas que nivelen el campo de juego. Esta perspectiva se basa en la idea de que la corrupción y la desigualdad están intrínsecamente vinculadas, y que la corrupción es vista como un mecanismo que exacerba las diferencias económicas entre grupos sociales. Por ejemplo, @bauhr_eu_2020 indican que en la Unión Europea la percepción de corrupción incrementa el apoyo por la redistribución en contextos en que existe una baja calidad de los gobiernos, pero no en contextos de gobiernos de alta calidad.

En el contexto de América Latina, @hauk_preception_2022 analizaron cómo la percepción de corrupción afecta el apoyo a la redistribución en 18 países de la región. Usando datos de LAPOP (2008-2012), encontraron que la corrupción percibida está positivamente relacionada con el apoyo a la redistribución. Esto indica que, aunque la corrupción disminuye la confianza en las instituciones públicas, la desigualdad económica domina: la corrupción incrementa la percepción de desigualdad y, por lo tanto, el deseo de redistribución. Estos hallazgos son robustos, incluso al corregir por endogeneidad y utilizando diferentes medidas de percepción de corrupción y apoyo a la redistribución. Por ejemplo, @morgan_explaining_2010 señalan que aquellos que perciben un aumento en la corrupción son más propensos a considerar la distribución de ingresos como injusta, lo que refuerza el deseo de redistribución. Este efecto puede estar relacionado con una creciente percepción de que la corrupción favorece a los ricos y perpetúa la desigualdad estructural. En esta línea, @cramer_views_2011 sugieren que, en la medida en que la corrupción es vista como un factor que distorsiona la equidad y el mérito, las personas tienden a considerar la desigualdad resultante como menos tolerable y, por ende, se inclinan más por políticas redistributivas que puedan corregir dichas distorsiones.

### Determinantes socioculturales

En un plano sociocultural, variados estudios han investigado la relación entre heterogeneidad social y apoyo a la reducción de desigualdades por medio del Estado. El argumento detrás de los estudios centrados en la fraccionalización étnica de los países está en que una menor percepción de afinidad de los contribuyentes para con los beneficiarios puede mermar la solidaridad de los primeros con los últimos y con ello su apoyo a las políticas redistributivas. Estudios como los de @luttmer_group_2001 y @finseraas_poverty_2012 han encontrado que divisiones culturales—sean étnicas, religiosas o nacionales—tienden a relacionarse negativamente con las preferencias redistributivas de las personas. En América Latina, existe evidencia que muestra que en países culturalmente más heterogéneos se presenta un menor apoyo a la redistribución, subrayando la importancia de la afinidad social en materia distributiva [@borges_selfinterest_2022]. Sin embargo, @berens_ethnic_2024 desafían la idea tradicional de que la diversidad sociocultural reduce el apoyo a los bienes públicos y la redistribución en la región. Sus resultados muestran que, en la mayoría de los casos, la heterogeneidad cultural no tiene un impacto significativo, lo que sugiere que la relación entre diversidad y preferencias redistributivas es más compleja de lo que se creía, y no necesariamente negativa.

En las últimas décadas, América Latina ha experimentado un aumento significativo en la migración intra-regional, impulsado por crisis sociales y económicas en países como Venezuela, Honduras y Haití [@cecchini_migracion_2023]. Este incremento migratorio ha transformado el panorama social y económico de la región. Al respecto, investigaciones como la de @martinezcorrea_latin_2022 encuentran que el aumento de la inmigración se asocia con una disminución en el apoyo a la redistribución. Utilizando una variedad de metodologías, incluyendo análisis transversal, modelos de efectos fijos y estudios de casos específicos como el éxodo venezolano a Colombia, el estudio revela que la inmigración tiende a reducir las preferencias por políticas redistributivas, especialmente entre individuos de altos ingresos y con alta calificación [@martinezcorrea_latin_2022]. Sorprendentemente, este efecto anti-redistributivo en América Latina es similar en tendencia al observado en los países desarrollados [@alesina_inmigration_2021; @dahlberg_ethnic_2012; @eger_even_2010], lo que indica que, incluso en contextos de mayor similitud cultural y económica, la inmigración puede influir significativamente en las preferencias sociales por las políticas de bienestar.

A pesar del creciente número de estudios centrados en América Latina, la mayor parte de la literatura sobre preferencias redistributivas sigue enfocada en países desarrollados, que paradójicamente enfrentan menores desafíos distributivos [@janmaat_subjective_2013]. Además, gran parte de la evidencia disponible se basa en datos previos a una serie de fenómenos que han tenido un impacto significativo en la vida de los ciudadanos y, probablemente, en sus preferencias. La emergencia sanitaria del COVID-19, el aumento de los flujos migratorios, las protestas masivas por demandas vinculadas a la desigualdad social, las crisis políticas y las reformas polémicas en la región son algunos de los hitos que subrayan la necesidad de integrar información reciente. Esto resulta fundamental para comprender mejor las tendencias, cambios y continuidades en el apoyo a la redistribución en América Latina.


