# Apéndice

## Cantidad de casos por país

```{r echo=FALSE, warning=FALSE, message=FALSE}
pacman::p_load(here, lme4, dplyr, kableExtra, stringr)
load(here("Input", "Proc", "LAPOP_Final.RData"))

# Renombrar variables
lapop = lapop %>% 
  mutate(Redistribution = redistribution,
         Income = decile,
         Male = male_f,
         Age = age, 
         Political = ideology_f, 
         Left = left, 
         SystemConfidence = sysconf, 
         Education = education_r, 
         Income_Decile = decile_f, 
         GINI = gini,
         GDP = gdp,
         GINI_BE = gini_mean, 
         GINI_WE = gini_dif, 
         GDP_BE = gdp_mean, 
         GDP_WE = gdp_dif,
         Welfare = welfare,
         Country = countryname,
         CountryWave = country_wave,
         Year = year,
         Decile_d10 = decile_d10,
         Decile_d1 = decile_d1,
         Income2 = Income * Income,
         Corrupcion = corruption) %>%
  mutate(across(where(haven::is.labelled), as.numeric))

tabla_casos <- lapop %>%
  group_by(country, year) %>%
  summarise(cantidad_casos = n()) %>%
  arrange(country, year)

tabla_casos <- tabla_casos %>%
  mutate(country = dplyr::recode(country,
                          "MEX" = "México",
                          "GTM" = "Guatemala",
                          "SLV" = "El Salvador",
                          "HND" = "Honduras",
                          "NIC" = "Nicaragua",
                          "CRI" = "Costa Rica",
                          "PAN" = "Panamá",
                          "COL" = "Colombia",
                          "ECU" = "Ecuador",
                          "BOL" = "Bolivia",
                          "PER" = "Perú",
                          "PRY" = "Paraguay",
                          "CHL" = "Chile",
                          "URY" = "Uruguay",
                          "BRA" = "Brasil",
                          "VEN" = "Venezuela",
                          "ARG" = "Argentina",
                          "DOM" = "República Dominicana"))

# Mostrar la tabla para PDF
tabla_casos %>%
  arrange(country, year) %>%  # Ordenar por país y año
  kable("latex", booktabs = TRUE, longtable = TRUE, col.names = c("País", "Año", "Cantidad de casos")) %>% 
  kable_styling(latex_options = c("hold_position", "repeat_header","scale_down")) %>%
  collapse_rows(columns = 1, valign = "middle")

?kableExtra::kable_styling()

```

## Tabla de regresión multinivel

```{r include=FALSE, results='asis'}
migracion = readRDS(here("input", "proc", "migracion.rds")) %>% 
  mutate(wave = as.character(wave))

lapop = lapop %>% 
  left_join(migracion)

```


```{r include=FALSE, results='asis'}
#Rename variables
lapop = lapop %>% 
  mutate(Redistribution = redistribution,
         Male = male_f,
         Age = age, 
         Income = decile,
         Income_Decile=decile_f, 
         Education=education_r, 
         Political = ideology_f, 
         Left = left, 
#         Married = married_f, 
         SystemConfidence=sysconf, 
#         Employment=employment_r, 
#         Urban=zone, 
         GINI=gini,
         GDP=gdp,
         GINI_BE=gini_mean, 
         GINI_WE=gini_dif, 
         GDP_BE=gdp_mean, 
         GDP_WE=gdp_dif,
         Welfare = welfare,
         Country = countryname,
         CountryWave = country_wave,
         Year = year,
         Decile_d10 = decile_d10,
         Decile_d1 = decile_d1,
         Income2 = Income*Income,
         Corrupcion = corruption,
          Migracion = migra) %>%
  mutate(across(where(haven::is.labelled), as.numeric))

```


```{r multilevel, echo=FALSE, results='asis'}
#| label: tbl-multilevel

# Model 1. Only years
model_1 = lmer(Redistribution ~ 1
                + Year + (1 | CountryWave) 
                + (1 | Country), data=lapop, weights=wt)

# Model 2. Individual predictors 
model_2 = lmer(Redistribution ~ 1 + Male + Age + Income + Education + 
                 Political + SystemConfidence  +
                Year + (1 | CountryWave) + (1 | Country), data=lapop, weights=wt)

# Model 3. Individual predictors + National predictors
model_3 = lmer(Redistribution ~ 1 + Male + Age + Income + Education + 
                 Political + SystemConfidence + GINI + GDP + Corrupcion + Migracion +
                Year + (1 | CountryWave) + (1 | Country), data=lapop, weights=wt)


# Table 1: individual

texreg::texreg(
  list(model_1, model_2, model_3),
  digits = 3,
  custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05.",
             custom.coef.names = c("Intercepto",
                                   "2010",
                                   "2012",
                                   "2014",
                                   "2016",
                                   "2018",
                                   "2023",
                                   "Hombre",
                                   "Edad",
                                   "Ingreso",
                                   "Secundaria",
                                   "Terciaria",
                                   "Centro",
                                   "Izquierda",
                                   "No declarada",
                                   "Confianza instituciones",
                                   "Desigualdad económica",
                                   "Desarrollo económico",
                                   "Corrupción",
                                   "Tasa de migración"),
  groups = list("Año (Referencia: 2008)" = 2:7,
                "Sexo (Referencia: Mujer)" = 8,
                "Educación (Referencia: Primaria)" = 11:12,
                "Identificación política (Referencia: Derecha)" = 13:15
                ),
  include.loglik = FALSE,
  include.aic = FALSE,
  custom.gof.names = c("BIC",
                       "Num. obs.",
                       "Num. groups: Año-país",
                       "Num. groups: País",
                       "Var: año-país (Intercepto)",
                       "Var: país (Intercepto)",
                       "Var: Residual"),
  center = TRUE,
  caption.above = TRUE,
  caption = "Tabla de regresión multinivel longitudinal",
  scalebox = 0.9,  # Ajuste del tamaño de la tabla
  booktabs = TRUE,  # Mejor formato para las tablas
  use.packages = FALSE,
  include.rs = FALSE, 
  include.rmse = FALSE,
  include.ci = FALSE
)

```
