---
bibliography: "input/bib/pref-redis-colmex.bib"
---

El contexto en donde viven las personas también tiene la capacidad de afectar su apoyo a las políticas redistributivas [@alesina_ethnic_2005; @kenworthy_inequality_2008; @svallfors_worlds_1997]. Si bien existen diferencias entre personas en función de sus características, también se han evidenciado grandes disparidades en el apoyo a la redistribución entre países y regiones del planeta. A nivel mundial, América Latina se ha tendido a posicionar como una de las regiones con mayor apoyo redistributivo [@dion_economic:_2010], a pesar de mostrar bajas en sus desigualdades económicas durante las últimas décadas [@holland_easy_2017; @lustig_declining_2013]. De todas formas, existe una importante heterogeneidad al interior de la región, con países con altas preferencias redistributivas—como Chile, Uruguay, Costa Rica y República Dominicana—y otros con bajo acuerdo con la redistribución—Venezuela, Paraguay, Ecuador y Bolivia, entre otros [@durakiewicz_reducing_2018]. Variados determinantes a nivel nacional en términos económicos, político-institucionales y socioculturales han sido relevados en el campo de la justicia distributiva, en búsqueda de explicar las variaciones en las preferencias redistributivas de las personas.

### Determinantes económicos

En términos económicos, uno de los factores mayormente estudiados es la desigualdad económica de los países. Desde la economía neoclásica, la previamente mencionada teoría del votante mediano de @meltzer_rational_1981 comenzó abordando esta relación, estableciendo que a medida que la desigualdad de los países es mayor, mayores serán las preferencias redistributivas de las personas. Según este enfoque, esta asociación estaría dada por una mayor distancia entre el votante de ingresos medianos respecto al votante de ingresos medios en contextos de mayor desigualdad, aumentando la población beneficiada por la redistribución y así su acuerdo con ella. Aunque algunos estudios han identificado una relación positiva entre la desigualdad y las preferencias redistributivas [@schmidtcatran_economic_2016], gran parte de la evidencia en torno a la justicia distributiva no encuentra una asociación clara [@bowles_reciprocity_2000; @luebker_income_2014], o incluso muestra un aumento en la tolerancia hacia la desigualdad en contextos donde esta es más pronunciada [@castillo_legitimacy_2010; @mijs_paradox_2019; @schroder_income_2017]. La falta de respaldo empírico hacia la teoría del votante mediano se explica por los supuestos en los que se basa: que los individuos son conscientes de la distribución de recursos en la sociedad y reconocen su posición relativa dentro de dicha distribución. Existe amplia evidencia que señala una desconexión entre la desigualdad real en los países y su percepción por parte de los ciudadanos [@bartels_unequal_2016; @gimpelson_misperceiving_2018; @kenworthy_inequality_2008; @trump_income_2023], así como sesgos en la autopercepción del estatus social, con una tendencia generalizada a ubicarse en las posiciones medias de la estructura social, aun cuando objetivamente no pertenezcan a dichos segmentos [@evans_subjective_2004].

Este aspecto guarda especial relevancia para América Latina, en tanto por décadas se ha ubicado como la región más desigual del planeta [@mann_explaining_2007]. Si bien se evidenció una disminución de sus niveles de inequidad económica durante los años 2000 [@holland_easy_2017; @lustig_declining_2013], en el presente Latinoamérica continúa situada entre las zonas con mayor desigualdad, siendo sólo superada sólo por África Subsahariana y Medio Oriente y Norte de África [@chancel_world_2022]. @franetovic_preferences_2022 evidenciaron las complejidades que la relación entre desigualdad objetiva y subjetiva presenta para la región. Sus análisis dan cuenta de la escasa aplicabilidad de teorías racionalistas clásicas, como la del votante mediano, en tanto países con mayor coeficiente GINI—indicador comúnmente utilizado para medir desigualdad económica—no se encuentra relacionado a una mayor demanda redistributiva por parte de las personas [@franetovic_preferences_2022]. Más allá de sus niveles agregados, sería la estructura de desigualdad la que podría jugar un rol más importante, referente a la distancia económica entre las clases medias, con respecto a aquellas ricas y pobres [@lupu_structure_2011]. En países de la región donde los estratos medios se ubican más próximos a las clases desposeídas, mayor tiende a ser el apoyo redistributivo de sus ciudadanos [@borges_selfinterest_2022].

Un determinante nacional menos estudiado, pero relevante en la configuración del apoyo a la redistribución, es el desarrollo económico de los países. Tal como lo propone @inglehart_silent_1971, el desarrollo económico generado a partir de los procesos de modernización de los países ha estado fuertemente vinculado a la promoción de valores postmaterialistas. El auge en la cobertura de necesidades básicas se asocia entonces a proyectos de vida menos determinados por cuestiones materiales económicas dando paso a otro tipo de preocupaciones entre las personas, enfocadas en la promoción de la autonomía y la satisfacción personal [@inglehart_changing_2008]. Justamente, estos son factores que @gelissen_popular_2000 ha visto estrechamente relacionados con las preferencias por redistribución de las personas. La evidencia muestra que América Latina ha visto una trayectoria similar entre modernización, valores postmaterialistas y acuerdo con la redistribución. @franetovic_preferences_2022 dan cuenta cómo, sostenidamente en el tiempo, los países más ricos de la región—Chile, Uruguay, Costa Rica y Panamá—concentran altos niveles de acuerdo con la redistribución, mientras que aquellos de menor PIB per cápita—Bolivia, Guatemala y Honduras—se caracterizan por tener poblaciones con bajas preferencias redistributivas. Un aspecto característico del mercado del trabajo en América Latina es la informalidad laboral [@jimenez_informalidad_2012]. 

La informalidad laboral en América Latina influye en las preferencias por la provisión de bienestar público. Por un lado, se ha visto que, al percibir a los trabajadores informales como free-riders, los trabajadores formales y las clases medias-altas prefieren que los servicios sociales se conviertan en bienes exclusivos, destinados solo a quienes contribuyen al sistema [@berens_exclusion_2015]. Por otra parte, se observa que en un contexto de segmentación laboral, a diferencia de lo esperado, los trabajadores informales en América Latina no muestran un mayor apoyo a las políticas redistributivas, incluso considerando sus riesgos económicos asociados [@berens_preferences_2015]. Esta compleja relación revela que, aunque la informalidad laboral genera tensiones —con los trabajadores formales inclinándose por excluir al sector informal de los beneficios del Estado—, sorprendentemente los trabajadores informales no son quienes impulsan un mayor apoyo a las políticas redistributivas.

### Determinantes político-institucionales

La literatura también reconoce la importancia de factores político-institucionales en el apoyo de las personas hacia la redistribución. El primero de ellos, comúnmente estudiado, corresponde al tipo de régimen de bienestar de los países. Según @espingandersen_three_1990, el estado de bienestar corresponde al conjunto de políticas sociales que determinan la desmercantilización de los individuos, la estratificación social y la relación entre Estado, mercado y familia. Considerando el origen del concepto, su discusión está marcada por una fuerte tradición occidental en países desarrollados. En ese contexto, se ha evidenciado que los regímenes de bienestar son importantes determinantes en las actitudes distributivas de las personas: mientras los regímenes socialdemócratas—universalistas y mayormente redistributivos—albergan un alto apoyo a la redistribución, en los liberales—subsidiarios y con acotada participación estatal en la provisión de servicios—éste tiende a ser mucho más acotado [@svallfors_worlds_1997].

Sin embargo, también se han visto desarrollos teóricos por generar una clasificación de regímenes de bienestar adaptada a la realidad latinoamericana, marcada por la existencia de zonas donde el Estado es prácticamente inexistente, una acotada porción de la población en el mercado laboral formal y grupos familiares y redes de apoyo como principales productores de bienestar [@gough_insecurity_2004]. Uno de los más destacados corresponde a la tipología desarrollada por @martinezfranzoni_welfare_2008. En función de sus niveles de mercantilización, desmercantilización y desfamiliarización, los países latinoamericanos son distinguidos entre regímenes productivistas, proteccionistas e informales-familiares. Si bien hasta la fecha no existen mayores intentos por analizar diferencias según regímenes de bienestar dentro de la región, @franetovic_preferences_2022 reportan que dicha distinción no estaría asociada a diferencias significativas en el apoyo a la redistribución de las personas al interior de la región.

También desde una arista político institucional, se ha revelado la importancia que tiene la confianza institucional al interior de los países [@yamamura_trust_2014]. Esto guarda especial relevancia en una región como América Latina, considerando la fragilidad de sus instituciones [@portes_institutions_2010] y los elevados y ascendentes índices de corrupción percibida por parte de sus ciudadanos [@transparency_global_2019]. @hauk_preception_2022 sugieren que la percepción de corrupción es capaz de influir sobre las preferencias redistributivas de dos formas: reduciéndolas, en tanto se duda de la efectividad y justicia de las intervenciones gubernamentales, pero también aumentándolas, en la medida que se percibe disminuida la riqueza personal en relación con el promedio. @franetovic_preferences_2022 avalan el primer punto, mostrando cómo mayores niveles de confianza en el sistema político por parte de las personas se asocian a significativas alzas en su apoyo a la redistribución. Todo esto, sumado a la importancia que manifiesta la creencia en que el Estado posee la capacidad para redistribuir [@busso_preferences_2023], pone en evidencia que en América Latina la discusión sobre preferencias redistributivas no debe estar exclusivamente en las características de los ciudadanos, sino en su relación de éstos últimos con sus instituciones públicas.

### Determinantes socioculturales

En un plano sociocultural, variados estudios han investigado la relación entre heterogeneidad social y apoyo a la reducción de desigualdades por medio del Estado. El argumento detrás de los estudios centrados en la fraccionalización étnica de los países está en que una menor percepción de afinidad de los contribuyentes para con los beneficiarios puede mermar la solidaridad de los primeros con los últimos y con ello su apoyo a las políticas redistributivas. Estudios como los de @luttmer_group_2001 y @finseraas_poverty_2012 han encontrado que divisiones culturales—sean étnicas, religiosas o nacionales—tienden a relacionarse negativamente con las preferencias redistributivas de las personas. En América Latina, existe evidencia que muestra que en países culturalmente más heterogéneos se presenta un menor apoyo a la redistribución, subrayando la importancia de la afinidad social en materia distributiva [@borges_selfinterest_2022]. Sin embargo, @berens_ethnic_2024 desafían la idea tradicional de que la diversidad sociocultural reduce el apoyo a los bienes públicos y la redistribución en la región. Sus resultados muestran que, en la mayoría de los casos, la heterogeneidad cultural no tiene un impacto significativo, lo que sugiere que la relación entre diversidad y preferencias redistributivas es más compleja de lo que se creía, y no necesariamente negativa.

En las últimas décadas, América Latina ha experimentado un aumento significativo en la migración intra-regional, impulsado por crisis sociales y económicas en países como Venezuela, Honduras y Haití [@cecchini_migracion_2023]. Este incremento migratorio ha transformado el panorama social y económico de la región. Al respecto, investigaciones como la de @martinezcorrea_latin_2022 encuentran que el aumento de la inmigración se asocia con una disminución en el apoyo a la redistribución. Utilizando una variedad de metodologías, incluyendo análisis transversal, modelos de efectos fijos y estudios de casos específicos como el éxodo venezolano a Colombia, el estudio revela que la inmigración tiende a reducir las preferencias por políticas redistributivas, especialmente entre individuos de altos ingresos y con alta calificación [@martinezcorrea_latin_2022]. Sorprendentemente, este efecto anti-redistributivo en América Latina es similar en tendencia al observado en los países desarrollados [@alesina_inmigration_2021; @dahlberg_ethnic_2012; @eger_even_2010], lo que indica que, incluso en contextos de mayor similitud cultural y económica, la inmigración puede influir significativamente en las preferencias sociales por las políticas de bienestar.

A pesar del creciente número de estudios centrados en América Latina, la mayor parte de la literatura sobre preferencias redistributivas sigue enfocada en países desarrollados, que paradójicamente enfrentan menores desafíos distributivos [@janmaat_subjective_2013]. Además, gran parte de la evidencia disponible se basa en datos previos a una serie de fenómenos que han tenido un impacto significativo en la vida de los ciudadanos y, probablemente, en sus preferencias. La emergencia sanitaria del COVID-19, el aumento de los flujos migratorios, las protestas masivas por demandas vinculadas a la desigualdad social, las crisis políticas y las reformas polémicas en la región son algunos de los hitos que subrayan la necesidad de integrar información reciente. Esto resulta fundamental para comprender mejor las tendencias, cambios y continuidades en el apoyo a la redistribución en América Latina.
