---
bibliography: "input/bib/pref-redis-colmex.bib"
---

### Corrupción

La relación entre corrupción y preferencias redistributivas ha recibido cierta atención en la literatura reciente, pero con resultados mixtos. Algunos estudios sugieren que la corrupción disminuye el apoyo a la redistribución, ya que la población puede desconfiar de que los recursos públicos sean utilizados de manera efectiva para reducir la desigualdad [@rothstein_all_2005]. La lógica detrás de esta argumentación es que, en contextos de alta corrupción, la ciudadanía percibe que el Estado es capturado por élites o grupos de poder, y, por tanto, es menos probable que las políticas redistributivas beneficien a los sectores más vulnerables. Como resultado, incluso aquellos que podrían beneficiarse de la redistribución podrían mostrarse escépticos hacia estas políticas. En América Latina, estudios recientes han explorado la relación entre estos factores, encontrando que la desconfianza en las instituciones y la percepción de corrupción afectan negativamente el apoyo a la redistribución [@holland_diminished_2018].

En contraste, otros estudios han argumentado que la percepción de corrupción puede incrementar la demanda de redistribución [@alesina_corruption_2005]. La lógica detrás de esta posición es que cuando la población percibe altos niveles de corrupción, también puede percibir que las desigualdades son producto de un sistema injusto, lo que incrementa el deseo de implementar políticas que nivelen el campo de juego. Esta perspectiva se basa en la idea de que la corrupción y la desigualdad están intrínsecamente vinculadas, y que la corrupción es vista como un mecanismo que exacerba las diferencias económicas entre grupos sociales. Por ejemplo, @bauhr_eu_2020 indican que en la Unión Europea la percepción de corrupción incrementa el apoyo por la redistribución en contextos en que existe una baja calidad de los gobiernos, pero no en contextos de gobiernos de alta calidad.

En el contexto de América Latina, @hauk_preception_2022 analizaron cómo la percepción de corrupción afecta el apoyo a la redistribución en 18 países de la región. Usando datos de LAPOP (2008-2012), encontraron que la corrupción percibida está positivamente relacionada con el apoyo a la redistribución. Esto indica que, aunque la corrupción disminuye la confianza en las instituciones públicas (canal de confianza), el canal de riqueza domina: la corrupción incrementa la percepción de desigualdad y, por lo tanto, el deseo de redistribución. Estos hallazgos son robustos, incluso al corregir por endogeneidad y utilizando diferentes medidas de percepción de corrupción y apoyo a la redistribución. Por ejemplo, @morgan_explaining_2010 señalan que aquellos que perciben un aumento en la corrupción son más propensos a considerar la distribución de ingresos como injusta, lo que refuerza el deseo de redistribución. Este efecto puede estar relacionado con una creciente percepción de que la corrupción favorece a los ricos y perpetúa la desigualdad estructural, similar al estudio realizado por @cramer_views_2011, donde sugieren que, en la medida en que la corrupción es vista como un factor que distorsiona la equidad y el mérito, las personas tienden a considerar la desigualdad resultante como menos tolerable y, por ende, se inclinan más por políticas redistributivas que puedan corregir dichas distorsiones.