---
title: "Preferences for income redistribution in unequal contexts: Changes in Latin America between 2008 and 2018"
subtitle: "Multilevel estimation"
date: "04-10-2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

+ Packages

```{r Packages, message=FALSE, warning=FALSE, include=FALSE}

#Install and load packages
pacman::p_load(tidyverse, lme4, stats, texreg, car, interplot, sjPlot, 
       data.table, influence.ME, performance, ggeffects, pals, data.table, 
       janitor, xtable, matrixStats, scales, ggthemes, here, conflicted,
       ggrepel)

#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("recode", "car")
conflict_prefer("melt", "data.table")

```

+ Load data 

```{r Database, echo=FALSE, message=FALSE, warning=FALSE}

#Load database
rm(list = ls())
load(here("Input", "Proc", "LAPOP_Final.RData"))

#Rename variables
lapop = lapop %>% 
  mutate(Redistribution = redistribution,
         Income = decile,
         Male = male_f,
         Age = age, 
         Political = ideology_f, 
         Left = left, 
#         Married = married_f, 
         SystemConfidence=sysconf, 
#         Employment=employment_r, 
         Education=education_r, 
#         Urban=zone, 
         Income_Decile=decile_f, 
         GINI=gini,
         GDP=gdp,
         GINI_BE=gini_mean, 
         GINI_WE=gini_dif, 
         GDP_BE=gdp_mean, 
         GDP_WE=gdp_dif,
         Welfare = welfare,
         Country = countryname,
         CountryWave = country_wave,
         Year = year,
         Decile_d10 = decile_d10,
         Decile_d1 = decile_d1,
         Income2 = Income*Income,
         Corrupcion = corruption)

```

# Null model, Cooks Distance and ICC

```{r Null model, echo=FALSE, message=FALSE, warning=FALSE}

#Null model: Country Year (with Venezuela)
model_0_ven = lmer(redistribution ~ 1 + (1 | country_wave) + (1 | countryname), data=lapop_all, weights=wt)
screenreg(model_0_ven, stars = c(0.01,0.05,0.1))

#Influence tests
inf.m0 = influence(model_0_ven, "countryname")

#Cook D
cooks.distance(inf.m0, parameter=1, sort=TRUE)

jpeg(here("Output", "Graphs", "CookD.jpg"), width=600, height=400)

plot(inf.m0, which="cook",
cutoff=.17, sort=TRUE,
xlab="Cook´s Distance",
ylab="Country", width=60, height=40)

while (!is.null(dev.list()))  dev.off()

#Null model: Country Year 
model_0 = lmer(Redistribution ~ 1 + (1 | CountryWave) + (1 |Country), data=lapop, weights=wt)
screenreg(model_0, stars = c(0.01,0.05,0.1))

#Intraclass correlation estimation (ICC)
performance::icc(model_0, by_group = TRUE)

# ICC (Country): 0.015
# ICC (CountryWave): 0.042
# ICC (individual): 0.943

```

# Multilevel estimation

```{r Multilevel estimation, echo=FALSE, message=FALSE, warning=FALSE}

# Model 1. Only income
model_1 = lmer(Redistribution ~ 1 + Income
                + Year + (1 | CountryWave) 
                + (1 | Country), data=lapop, weights=wt)

# Model 2. Individual predictors 
model_2 = lmer(Redistribution ~ 1 + Income + Male + Age  
                + Political + SystemConfidence + Education 
                + Year + (1 | CountryWave) + (1 | Country), data=lapop, weights=wt)

# Model 3. Individual predictors + GINI  + GDP
model_3 = lmer(Redistribution ~ 1 + Income + Male + Age 
                + Political + SystemConfidence + Education 
                + GINI
                + GDP + Year
                + (1 | CountryWave) + (1 | Country), data=lapop, weights=wt)

# Model 4. Individual predictors + GINI + GDP (Income)
model_4 = lmer(Redistribution ~ 1 + Income + Male + Age 
                + Political + SystemConfidence + Education 
                + GINI
                + GDP + Year
                + Corrupcion
                + (1 | CountryWave) + (1 | Country), data=lapop, weights=wt)

#Table
screenreg(list(model_1, model_2, model_3, model_4), digits = 3)
```

# Cross-level interactions

```{r Cross-level interactions, echo=FALSE, message=FALSE, warning=FALSE}

# Model 5: Individual predictors + GINI + GDP (Random Income) + Income*GINI
model_5 = lmer(Redistribution ~ 1 + Income + Male + Age + Married 
                + Political + SystemConfidence + Employment + Education 
                + Urban + GINI_BE + GINI_WE
                + GDP_BE + GDP_WE
                + Income*GINI_BE + Income*GINI_WE + Year
                + (1 + Income | CountryWave) + (1 + Income | Country), data=lapop, weights=wt)

# Model 6: Individual predictors + GINI + GDP (Random Income) + Income*GDP
model_6 = lmer(Redistribution ~ 1 + Income + Male + Age + Married 
                + Political + SystemConfidence + Employment + Education 
                + Urban + GINI_BE + GINI_WE
                + GDP_BE + GDP_WE
                + Income*GDP_BE + Income*GDP_WE + Year
                + (1 + Income | CountryWave) + (1 + Income | Country), data=lapop, weights=wt)

#Table
screenreg(list(model_5, model_6),  stars = c(0.01,0.05,0.1), digits = 3)

```

# Random effect of income

```{r Random effect of income, echo=FALSE, message=FALSE, warning=FALSE}

#Figure 6: Income random effect on support for redistribution by country: intercept and slope
figure_6 = plot_model(model_4, type = "re", 
                   show.legend = FALSE,
                   show.values = TRUE,
                   facet.grid = FALSE,
                   y.offset = .4,
                   value.offset = .4,
                   value.size = 3.5,
                   sort.est= "Income",
                   title = " ") 

figure_6a = figure_6[[2]] + 
  scale_y_continuous(limits = c(-0.4, 0.4)) + 
  scale_color_grey(start=0.6, end=0.2) + 
  theme(panel.grid = element_line(colour = "grey"), 
        panel.grid.major.y = element_line(colour = "grey"),panel.background = element_rect(fill = "white")) + 
  geom_hline(yintercept = 0, linetype = "dashed")

figure_6a
ggsave(here("Output", "Graphs", "Figure6.jpg"), plot=figure_6a, height = 5, units="in")

ranef(model_6)


#Alternative figure
me = ggpredict(model_4, terms = c("Income", "Country"), type = "re")

figure_6b = plot(me, 
                 show.title = FALSE) +
  labs(
    x = "Income (deciles)", 
    y = "Support for redistribution", 
    title = " "
  )  +
  scale_x_continuous("Income (deciles)", limits = c(1,10), breaks = c(1,2,3,4,5,6,7,8,9,10)) +
  theme(panel.grid.minor.x = element_blank()) + 
  scale_fill_manual(values=as.vector(polychrome(17)))

figure_6b

# ggsave("../Output/Graphs/Figure_6b.jpg", plot=figure_6b)

```

# Cross-level interactions: Predicted values

```{r Predicted values, echo=FALSE, message=FALSE, warning=FALSE}

#GINI [WE]
int_inc_ine = ggpredict(model_5, terms = c("Income", "GINI_WE [-3.97, 4.93]"))

figure_7a = plot(int_inc_ine, 
                 show.title = FALSE, ci.style = "errorbar", dot.size = 2.5) +
  labs(
    x = "Income (deciles)", 
    y = "Support for redistribution", 
    title = " ",
    colour ="GINI[WE]"
  )  +
  scale_x_continuous("Income (deciles)", limits = c(0.9,10.1), breaks = c(1,2,3,4,5,6,7,8,9,10)) +
  theme(panel.grid.minor.x = element_blank()) +
  scale_y_continuous("Support for redistribution", limits = c(5, 6.5), breaks = c(5, 5.5, 6, 6.5)) +
  scale_colour_grey(start=0.6, end=0.1, name="GINI[WE]", labels = c("Max decrease", "Max increase"))

figure_7a
ggsave(here("Output", "Graphs", "Figure7a.jpg"), plot=figure_7a, height = 3.8, units="in")

#GDP [BE]
int_inc_dev = ggpredict(model_6, terms = c("Income", "GDP_BE [1.65, 13.98]"))

figure_7b = plot(int_inc_dev, 
                 show.title = FALSE, ci.style = "errorbar", dot.size = 1.5) +
  labs(
    x = "Income (deciles)", 
    y = "Support for redistribution", 
    title = " ",
    colour ="GDP[BE]"
  )  +
  scale_x_continuous("Income (deciles)", limits = c(0.9,10.1), breaks = c(1,2,3,4,5,6,7,8,9,10)) +
  theme(panel.grid.minor.x = element_blank())  +
  scale_y_continuous("Support for redistribution", limits = c(5, 6.5), breaks = c(5, 5.5, 6, 6.5)) +
  scale_colour_grey(start=0.6, end=0.1, name="GDP[BE]", labels = c("Low", "High"))

figure_7b
ggsave(here("Output", "Graphs", "Figure7b.jpg"), plot=figure_7b, height = 3.8, units="in")


#Detach package conflicted
detach("package:conflicted", unload = TRUE)

```


